---
- name: RESPALDO IPV6 LOOPBACK 33
  hosts: CSR1kv
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Ejecutar 'show running-config'
      ios_command:
        commands:
          - show running-config
      register: config

    - name: Guardar salida localmente
      copy: 
        content: "{{ config.stdout[0] }}"
        dest: "respaldo/IPv6_Loopback33_{{ inventory_hostname }}.txt"

