---
- name: CONFIGURACION IPV6 LOOPBACK 33
  hosts: CSR1kv
  gather_facts: false
  connection: network_cli

  tasks:
   - name: SET IPv6 ADDRESS LOOPBACK 33
     ios_config:
       lines:
         - interface Loopback33
         - description Loopback33 ipv6 con ansible
         - ipv6 address 3001:ABCD:ABCD:1::1/128
         - ipv6 address FE80::1 link-local
